# Github actions workflow for linting content related to this repo
---
name: lint docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: abatilo/actions-poetry@v2.1.3
      - name: install
        run: poetry install
      - name: Lint documentation
        run: poetry run sphinx-lint